# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('orderdate', models.DateTimeField()),
                ('token', models.CharField(max_length=30)),
                ('paymentstatus', models.IntegerField(choices=[(0, b'Not Charged'), (1, b'Charged'), (2, b'Failed')])),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_demo.Product')),
            ],
        ),
    ]
