# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_demo', '0003_auto_20170202_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='productid',
            new_name='product',
        ),
    ]
