# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_demo', '0004_auto_20170202_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentstatus',
            field=models.IntegerField(choices=[(0, b'UNPAID'), (1, b'PAID'), (2, b'FAILED')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='userid',
            field=models.CharField(max_length=255),
        ),
    ]
