# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_demo', '0006_auto_20170205_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='userid',
            new_name='user',
        ),
    ]
